Add email init script
Signed-off-by: Yubin Yan <yyan@redhat.com>

diff --git a/revokd b/revokd
--- a/revokd
+++ b/revokd
@@ -5,12 +5,96 @@ NULL="> /dev/null 2>&1"
 
 . $ROOT_PATH/bin/setenv.sh
 
+set_smtp(){
+  mail_reg="^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$"
+  server_reg="^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$"
+  port_reg="[0-9]{1,5}"
+  while true; do
+    echo "To send you scan report, we need your email:"
+    read email
+    email="${email,,}"
+
+    if [[ $email =~ $mail_reg ]]; then
+      break
+    else
+      echo "Invalid email address, please try again"
+    fi
+  done
+
+  domain=$(echo $email | grep -Eo '[^@]+$')
+
+  server_name=$(awk "/$domain/{print \$2}" $ROOT_PATH/conf/smtp_list.txt)
+  port=$(awk "/$domain/{print \$3}" $ROOT_PATH/conf/smtp_list.txt)
+  if [ -z $server_name ]; then
+    echo "It seems not a common domain, we need the smtp server name of this domain:"
+    while true; do
+      read server_name
+      server_name="${server_name,,}"
+      if [[ $server_name =~ $server_reg ]]; then
+        break
+      else
+        echo "Invalid server name, try again please"
+      fi
+    done
+    while true; do
+      echo "The smtp port of the server:"
+      read port
+      if [[ $port =~ $port_reg ]]; then
+        break
+      else
+        echo "Invalid port number, try again please"
+      fi
+    done
+  fi
+  while true; do
+    echo "The password to login your email:"
+    read -s password
+    if [ ! -z $password ]; then
+      break
+    else
+      echo "Invalid port number, try again please"
+    fi
+  done
+  username=${email/"@"$domain/""}
+
+  key="SMTP_ADDRESS"
+  sed -i "s/\($key *= *\).*/\1$server_name/" $ROOT_PATH/conf/revok.conf
+
+  key="SMTP_PORT"
+  sed -i "s/\($key *= *\).*/\1$port/" $ROOT_PATH/conf/revok.conf
+
+  key="SMTP_USER"
+  sed -i "s/\($key *= *\).*/\1$username/" $ROOT_PATH/conf/revok.conf
+
+  key="SMTP_PASSWORD"
+  sed -i "s/\($key *= *\).*/\1$password/" $ROOT_PATH/conf/revok.conf
+
+  key="EMAIL_ADDRESS"
+  sed -i "s/\($key *= *\).*/\1$email/" $ROOT_PATH/conf/revok.conf
+}
+
 init() {
   # Pre-init check
   # JRE check
   echo -en "Check JRE installation..."
-  which java > /dev/null || exit 1
+  which java > /dev/null
+  if [ $? == 1 ]; then
+    echo "Please install Java Runtime Environment at first"
+    exit 1
+  fi
   echo "done"
+
+  # Tcl check
+  echo -en "Check Tcl installation..."
+  which tclsh > /dev/null
+  if [ $? == 1 ]; then
+    echo "Please install Tcl at first"
+    exit 1
+  fi
+  echo "done"
+
+  # Init SMTP config
+  set_smtp
 
   # Make dirs
   echo -en "Make directories..."
@@ -34,7 +118,7 @@ init() {
   echo "done"
 
   # Config iptables
-  echo "Config iptables, may need the password for root..."
+  echo "Configure iptables, may need the password for root..."
   su - -c "iptables -I INPUT 1 -p tcp -m tcp --dport $AMPQ_PORT -j ACCEPT;
   iptables -I INPUT 1 -p tcp -m tcp --dport $DB_PORT -j ACCEPT;
   iptables -I INPUT 1 -p tcp -m tcp --dport $REST_PORT -j ACCEPT;
